server:
  port: 5000
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/database_name?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  mail:
    host: smtp.gmail.com
    username: gmail@gmail.com
    password: password
    port: 465

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    testConnection: true
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
logging:
  level:
    org:
      hibernate:
        sql: debug